providers = ["node@20"]

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]
env = {
  VITE_INSFORGE_URL = "https://demo-youtube-minimax.apps.devtik.xyz",
  VITE_INSFORGE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3OC0xMjM0LTU2NzgtOTBhYi1jZGVmMTIzNDU2NzgiLCJlbWFpbCI6ImFub25AaW5zZm9yZ2UuY29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2NTMxNzB9.N5nN3Nb58iKfeY5j5VYWc-ww_ZZqJQFHvR4SkvkNxew"
}

[start]
cmd = "npm start"